service: my-project

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment:
    REGION: self:provider.region

  # Describe necessary IAM permissions here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  helloWolf:
    handler: main.helloWolf
    events:
      - http:
          path: api
          method: get
